### ISSUE TITLE
Encoder Version

### ISSUE THREAD

**Issue by abcp4** [bobby-he/simplified_transformers#3]
The paper report an encoder version(adapted from the cramming one) of the simplified transformer block. Any plans to disponibilize this code? If not, what changes one has to do to adapt from this decoder version?

**Comment by bobby-he** [comment]
I haven't had much time and it's not high on my

**Comment by bobby-he** [comment]
I haven't had the time and it's not high on my list. The only change from the decoder version is to change the centering matrix in shaped attention, which is always defined as the post-softmax matrix with zero Q-K dot product. For encoder only with no causal masking (and assuming no other masking, i.e the masking is in the embeddings), then the centering matrix is just the uniform stochastic matrix (i.e. 1/T uniform entries, for sequence length T).
